Repository code-4-u/beauty-4-u-BE-Flask, pull requests merged in 2024-12, with the labels that each got.

#3 docs: 깃 이슈 템플릿 추가 #2
  .github/ISSUE_TEMPLATE/✅이슈-생성-템플릿.md
  .github/ISSUE_TEMPLATE/기능구현.md
  .github/ISSUE_TEMPLATE/리팩토링.md
  .github/ISSUE_TEMPLATE/문서화.md
  .github/ISSUE_TEMPLATE/버그수정.md
  .github/ISSUE_TEMPLATE/스타일.md
  .github/ISSUE_TEMPLATE/자잘한수정.md
  .github/ISSUE_TEMPLATE/테스트.md
  .github/ISSUE_TEMPLATE/파일수정.md
Labels: docs

#4 feat: apriori 기본 구조 설정
  .github/pull_request_template.md
  .gitignore
  .idea/.gitignore
  .idea/beauty-4-u-BE-Flask.iml
  .idea/dataSources.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  app.py
  config/__init__.py
  controller/__init__.py
  controller/apriori_controller.py
  model/__init__.py
  model/analysis.py
  model/db.py
  model/enums.py
  repository/__init__.py
  requirements.txt
  service/__init__.py
  service/apriori_service.py
Labels: feat

#6 feat: db 연결 오류 해결 및 기본 apriori 구조 구현
  .idea/beauty-4-u-BE-Flask.iml
  .idea/misc.xml
  app.py
  model/analysis.py
  model/db.py
  model/enums.py
  repository/apriori_repository.py
  service/apriori_service.py
Labels: feat

#9 feat: apriori 알고리즘을 사용한 조합 분석 기능 구현
  controller/apriori_controller.py
  model/analysis.py
  model/enums.py
  requirements.txt
  service/apriori_service.py
Labels: feat, refactor

#11 협업필터링 구현
  .gitignore
  app.py
  controller/collaboFilter_controller.py
  evaluation/HybridRecommenderEvaluator.py
  model/analysis.py
  requirements.txt
  service/collaboFilter_service.py
Labels: feat

#14 Collabo filter DB 저장 구현
  controller/collaboFilter_controller.py
  service/collaboFilter_service.py
Labels: feat

#13 chore: apriori 분석 로직 수정
  model/analysis.py
  service/apriori_service.py
Labels: refactor, chore

#16 refactor: 파이선 일부 수정#15
  app.py
  model/analysis.py
  service/collaboFilter_service.py
Labels: refactor

#19 refactor: 컨트롤러 반환 값 설정함. #18
  controller/collaboFilter_controller.py
Labels: refactor

#20 refactor: 연관분석 리팩토링
  .idea/beauty-4-u-BE-Flask.iml
  .idea/dataSources.xml
  .idea/git_toolbox_blame.xml
  .idea/git_toolbox_prj.xml
  .idea/material_theme_project_new.xml
  .idea/misc.xml
  Dockerfile
  app.py
  controller/apriori_controller.py
  docker-compose.yml
  model/analysis.py
  model/db.py
  requirements.txt
  service/apriori_service.py
Labels: refactor
